# These are supported funding model platforms

github: Comp-Labs
patreon: complabs
open_collective: comp-labs
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: complabs
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: 'https://rzp.io/l/CLDonations/', 'https://paypal.me/complabs28'
